### ISSUE TITLE
Multiple RbInterpreters

### ISSUE THREAD

**Issue by chendo** [Anyolite/anyolite#26]
I'm considering using anyolite for a use case where performance matters and I was hoping to create a pool of `RbInterpreters` to ensure the setup does not delay actual execution. However, the current implementation only allows for one.

Are there plans to enable support for multiple `RbInterpreters`? I reckon this work would also good for when multithreading is enabled by default too

**Comment by Hadeweka** [comment]
This would really be cool feature to have, and I already thought about it a bit, but I'm not yet 100% sure how to realize it.

For single-threaded applications this is no problem, but multithreading opens up some problems (like communicating between the interpreters and how to handle memory management for shared data).

There are also some implementation details that might cause problems, but in theory this should work somehow.

Maybe I'll put this on the list for the 1.2.0, but I need to think a bit more about how to solve this.

**Comment by chendo** [comment]
I think it would be good to not have the interpreters interoperate themselves. In my use case, the interpreters won't be sharing data between them.

I'm not very familiar with Crystal yet but I am interested in contributing if I am able to! I think combining mruby with Crystal opens up very interesting use cases

**Comment by Hadeweka** [comment]
I will close this issue for now, as I move the feature discussion to https://github.com/Anyolite/anyolite/discussions/28.
