### ISSUE TITLE
MRI build process has several warnings

### ISSUE THREAD

**Issue by mistergibson** [Anyolite/anyolite#32]
glue/mri/error_helper.c: In function ‘rb_raise_runtime_error’:
glue/mri/error_helper.c:5:3: warning: format not a string literal and no format arguments [-Wformat-security]
    5 |   rb_raise(rb_eRuntimeError, msg);
      |   ^~~~~~~~
glue/mri/error_helper.c: In function ‘rb_raise_type_error’:
glue/mri/error_helper.c:11:3: warning: format not a string literal and no format arguments [-Wformat-security]
   11 |   rb_raise(rb_eTypeError, msg);
      |   ^~~~~~~~
glue/mri/error_helper.c: In function ‘rb_raise_argument_error’:
glue/mri/error_helper.c:17:3: warning: format not a string literal and no format arguments [-Wformat-security]
   17 |   rb_raise(rb_eArgError, msg);
      |   ^~~~~~~~
glue/mri/error_helper.c: In function ‘rb_raise_index_error’:
glue/mri/error_helper.c:23:3: warning: format not a string literal and no format arguments [-Wformat-security]
   23 |   rb_raise(rb_eIndexError, msg);
      |   ^~~~~~~~
glue/mri/error_helper.c: In function ‘rb_raise_range_error’:
glue/mri/error_helper.c:29:3: warning: format not a string literal and no format arguments [-Wformat-security]
   29 |   rb_raise(rb_eRangeError, msg);
      |   ^~~~~~~~
glue/mri/error_helper.c: In function ‘rb_raise_name_error’:
glue/mri/error_helper.c:35:3: warning: format not a string literal and no format arguments [-Wformat-security]
   35 |   rb_raise(rb_eNameError, msg);
      |   ^~~~~~~~
glue/mri/error_helper.c: In function ‘rb_raise_script_error’:
glue/mri/error_helper.c:41:3: warning: format not a string literal and no format arguments [-Wformat-security]
   41 |   rb_raise(rb_eScriptError, msg);
      |   ^~~~~~~~
glue/mri/error_helper.c: In function ‘rb_raise_not_implemented_error’:
glue/mri/error_helper.c:47:3: warning: format not a string literal and no format arguments [-Wformat-security]
   47 |   rb_raise(rb_eNotImpError, msg);
      |   ^~~~~~~~
glue/mri/error_helper.c: In function ‘rb_raise_key_error’:
glue/mri/error_helper.c:53:3: warning: format not a string literal and no format arguments [-Wformat-security]
   53 |   rb_raise(rb_eKeyError, msg);
      |   ^~~~~~~~
glue/mri/error_helper.c: In function ‘rb_raise_helper’:
glue/mri/error_helper.c:59:3: warning: format not a string literal and no format arguments [-Wformat-security]
   59 |   rb_raise(exc, msg);
      |   ^~~~~~~~

**Comment by Hadeweka** [comment]
Fixed in the most recent main commit.
