### ISSUE TITLE
How and where do I set anyolite_implementation_ruby_3 ??? Docs mighty scant

### ISSUE THREAD

**Issue by mistergibson** [Anyolite/anyolite#33]
Hey There,

I'm trying to set the anyolite_implementation_ruby_3 flag but docs don't say how/where/when to set it

Looking for some hints.

**Comment by Hadeweka** [comment]
Also please consider choosing a more objective wording for your issues.

Expressions like "Docs mighty scant" are rude and far from objective. If you are frustrated with something, harsh language will not make me fix the issue faster.
