### ISSUE TITLE
interfacng issue --> suspect mapping problem

### ISSUE THREAD

**Issue by mistergibson** [Anyolite/anyolite#34]
Howdy,

I defined this:

  module External
    def self.argv()
      ::ARGV
    end
    def self.output(the_string : String =  "") : Nil
      puts the_string.to_s
    end
  end

then I wrap the module on the interpreter instance.

But when I call External.output the following happens:

if I supply a string it raises an error  stating that 0 args were expected

I've done my level best to declare the interface -- am I doing something wrong?

the intent is that I pass a string from ruby back into crystal.

**Comment by Hadeweka** [comment]
You need to pass the keyword arguments explicitly from Ruby to Crystal unless you annotate the methods explicitly.

See https://github.com/Anyolite/anyolite/wiki/Code-guidelines-and-workarounds#non-keyword-arguments for details.

I could change this per default to one of the options described there, but this would break backward compatibility, so this won't happen until Anyolite 2.0.0.
