### ISSUE TITLE
anyolite and mruby-win32ole

### ISSUE THREAD

**Issue by dsisnero** [Anyolite/anyolite#43]
Error trying to use with mruby-win32ole 
[myrepo](https://github.com/dsisnero/any_ole)

Steps - 

1. added dependency to anyolite to shard.yml
2.  ran shards install
3.  opened a visual studio development prompt
4.  cd to lib\anyolite
5. added conf.gem github: "sdottaka/mruby-win32ole" to utility/mruby_build_config.rb
6. ran rake build_shard - ran successfully
7.  changed back to any_ole directory
8.  build and create gist with error  - shards build | gh gist create -d "shards build

[error returned](https://gist.github.com/dsisnero/35afa6a9a27fcd81a52ea2f3605cf91f)

**Comment by Hadeweka** [comment]
You still need to link against user32.lib and oleaut32.lib. For example, you can pass `--link-flags="user32.lib oleaut32.lib"` to the crystal compiler, then it should work.

**Comment by Hadeweka** [comment]
Happy to hear that! 😃 

I will close this issue then. If something else makes problems, just open a new issue.
